### ISSUE TITLE
I have to ask because I added these lines

### ISSUE THREAD

**Issue by Algester** [balance19/micropython_DS3231#3]
under class RTC
m = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]

under def DS3231_ReadTime
month = self.m[self.bcd2bin(buffer[5])]

in if mode ==
            if mode == 2:
                mod2_string = str(hour) + ":" + str(minute) + ":" + str(second) + "        " + weekday + " " + month + "." + str(day) + "," + str(year)
                return mod2_string

and finally change 1     
t = rtc.DS3231_ReadTime(2)
yet after slapping it into my raspberry pi pico I'm getting the Error: Is the DS3231 not connected display on a 1602 LCD

**Comment by jose1711** [comment]
Your example is working for me. Next time please fork the repository, do the changes and refer to your branch. I suspect there is a formatting issue in the `try` block so perhaps modify `except` as follows:
```
except Exception as e:
    return "Error: is the DS3231 not connected or some other problem (%s)" % e
```

**Comment by balance19** [comment]
Thank you! I added your lines to the code.
